### ISSUE TITLE
comments...

### ISSUE THREAD

**Issue by heavyk** [yhsiang/language-livescript#1]
hi, when I press `cmd+/` it will insert the highlighted code into comments `/* ... */`

however, I would rather it does like the sublime version: it iterates over each line, adding a `#` in front of each one... how can I do that? I looked at the code and found the comment blocks, but I'm not totally sure how to make it do what I want... any help would be appreciated.

thanks :) - just getting into atom and though there's a bit of slowdown in comparison to sublime, but first impression is, it's pretty cool... cheers

**Comment by legomind** [comment]
+1 for me, big slowdown for repeat commenting

**Comment by legomind** [comment]
+1 for me as well, multiline comments can cause syntax errors in some cases where single line comments will do just fine

**Comment by legomind** [comment]
I manually installed this repo@master into atom and comments are now working correctly.

Please increment version and publish to atom.io

**Comment by blvz** [comment]
Just marketing my fork:
https://github.com/blvz/language-livescript-edge

Comments work as expected. Also, highlighting and snippets were improved. I'll be updating this regularly, since I code in LiveScript almost every day.

**Comment by bumxu** [comment]
An update will be published soon.
@heavyk if you continue experimenting problems post them here.
Thank you!
