### ISSUE TITLE
It's considering parts of identifiers as keywords

### ISSUE THREAD

**Issue by dead-claudia** [yhsiang/language-livescript#7]
I think this screen clipping should show the problem well enough.

![image](https://cloud.githubusercontent.com/assets/4483844/8207025/735d466c-14cc-11e5-8b1a-650b5a804429.png)

**Comment by bumxu** [comment]
The problem seems to be solved. If you could confirm it better!
Your example included a new issue 😛, #10.

**Comment by bumxu** [comment]
And more...

![captura de pantalla 2016-06-15 a las 0 12 23](https://cloud.githubusercontent.com/assets/1742635/16061566/de6be460-328d-11e6-8ead-5c4933dcc4c2.png)

**Comment by bumxu** [comment]
Ok, for now looks good...

![captura de pantalla 2016-06-15 a las 1 56 27](https://cloud.githubusercontent.com/assets/1742635/16063829/65207530-329c-11e6-8d3c-21c5774cc3ef.png)

Feel free to reopen if necessary.
Thank you for your support.
🚧
